<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class recipesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    DB::table('recipes')->insert([
        [
            'title' => 'Spaghetti Carbonara',
            'slug' => 'spaghetti-carbonara',
            'people_id' => 1,
            'rating' => 4.5,
            'category_id' => 2,
            'cuisine_id' => 1,
            'media_id' => 3,
            'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
            'nutrition' => json_encode(['calories' => 400, 'protein' => 15, 'fat' => 10]),
            'prepare_time' => 10,
            'total_time' => 30,
            'cooking_time' => 20,
            'servings' => 4,
            'steps' => json_encode(['Boil pasta', 'Cook pancetta', 'Mix eggs and cheese', 'Combine all ingredients']),
            'cost' => 15.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Chicken Curry',
            'slug' => 'chicken-curry',
            'people_id' => 2,
            'rating' => 4.8,
            'category_id' => 3,
            'cuisine_id' => 2,
            'media_id' => 5,
            'description' => 'A flavorful and spicy chicken curry made with a blend of aromatic spices.',
            'nutrition' => json_encode(['calories' => 500, 'protein' => 25, 'fat' => 20]),
            'prepare_time' => 15,
            'total_time' => 45,
            'cooking_time' => 30,
            'servings' => 6,
            'steps' => json_encode(['Marinate chicken', 'Prepare curry base', 'Cook chicken in curry', 'Simmer until done']),
            'cost' => 20.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Beef Stroganoff',
            'slug' => 'beef-stroganoff',
            'people_id' => 3,
            'rating' => 4.7,
            'category_id' => 4,
            'cuisine_id' => 3,
            'media_id' => 7,
            'description' => 'A creamy and savory beef dish served with noodles or rice.',
            'nutrition' => json_encode(['calories' => 600, 'protein' => 30, 'fat' => 25]),
            'prepare_time' => 20,
            'total_time' => 50,
            'cooking_time' => 30,
            'servings' => 5,
            'steps' => json_encode(['Sauté beef', 'Prepare sauce', 'Combine beef and sauce', 'Serve over noodles']),
            'cost' => 18.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Vegetable Stir Fry',
            'slug' => 'vegetable-stir-fry',
            'people_id' => 4,
            'rating' => 4.3,
            'category_id' => 5,
            'cuisine_id' => 4,
            'media_id' => 9,
            'description' => 'A quick and healthy stir fry with fresh vegetables and a savory sauce.',
            'nutrition' => json_encode(['calories' => 250, 'protein' => 5, 'fat' => 8]),
            'prepare_time' => 10,
            'total_time' => 20,
            'cooking_time' => 10,
            'servings' => 3,
            'steps' => json_encode(['Chop vegetables', 'Prepare sauce', 'Stir fry vegetables', 'Add sauce and serve']),
            'cost' => 10.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Pancakes',
            'slug' => 'pancakes',
            'people_id' => 5,
            'rating' => 4.6,
            'category_id' => 6,
            'cuisine_id' => 5,
            'media_id' => 11,
            'description' => 'Fluffy and delicious pancakes perfect for breakfast.',
            'nutrition' => json_encode(['calories' => 300, 'protein' => 6, 'fat' => 10]),
            'prepare_time' => 5,
            'total_time' => 15,
            'cooking_time' => 10,
            'servings' => 4,
            'steps' => json_encode(['Mix ingredients', 'Heat pan', 'Cook pancakes', 'Serve with syrup']),
            'cost' => 8.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Caesar Salad',
            'slug' => 'caesar-salad',
            'people_id' => 6,
            'rating' => 4.4,
            'category_id' => 7,
            'cuisine_id' => 6,
            'media_id' => 13,
            'description' => 'A classic salad with romaine lettuce, croutons, and Caesar dressing.',
            'nutrition' => json_encode(['calories' => 200, 'protein' => 7, 'fat' => 12]),
            'prepare_time' => 10,
            'total_time' => 10,
            'cooking_time' => 0,
            'servings' => 2,
            'steps' => json_encode(['Chop lettuce', 'Prepare dressing', 'Toss salad', 'Add croutons and serve']),
            'cost' => 7.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Tomato Soup',
            'slug' => 'tomato-soup',
            'people_id' => 7,
            'rating' => 4.2,
            'category_id' => 8,
            'cuisine_id' => 7,
            'media_id' => 15,
            'description' => 'A warm and comforting tomato soup made with fresh tomatoes.',
            'nutrition' => json_encode(['calories' => 150, 'protein' => 3, 'fat' => 5]),
            'prepare_time' => 10,
            'total_time' => 30,
            'cooking_time' => 20,
            'servings' => 4,
            'steps' => json_encode(['Chop tomatoes', 'Cook tomatoes with spices', 'Blend soup', 'Serve hot']),
            'cost' => 6.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Grilled Cheese Sandwich',
            'slug' => 'grilled-cheese-sandwich',
            'people_id' => 8,
            'rating' => 4.5,
            'category_id' => 9,
            'cuisine_id' => 8,
            'media_id' => 17,
            'description' => 'A crispy and gooey grilled cheese sandwich.',
            'nutrition' => json_encode(['calories' => 400, 'protein' => 10, 'fat' => 20]),
            'prepare_time' => 5,
            'total_time' => 10,
            'cooking_time' => 5,
            'servings' => 1,
            'steps' => json_encode(['Butter bread', 'Add cheese', 'Grill sandwich', 'Serve hot']),
            'cost' => 5.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Chocolate Cake',
            'slug' => 'chocolate-cake',
            'people_id' => 9,
            'rating' => 4.9,
            'category_id' => 10,
            'cuisine_id' => 9,
            'media_id' => 19,
            'description' => 'A rich and moist chocolate cake perfect for dessert.',
            'nutrition' => json_encode(['calories' => 450, 'protein' => 6, 'fat' => 18]),
            'prepare_time' => 20,
            'total_time' => 60,
            'cooking_time' => 40,
            'servings' => 8,
            'steps' => json_encode(['Mix ingredients', 'Bake cake', 'Prepare frosting', 'Frost cake and serve']),
            'cost' => 12.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Tacos',
            'slug' => 'tacos',
            'people_id' => 10,
            'rating' => 4.7,
            'category_id' => 11,
            'cuisine_id' => 10,
            'media_id' => 21,
            'description' => 'A Mexican dish with a variety of fillings wrapped in a tortilla.',
            'nutrition' => json_encode(['calories' => 300, 'protein' => 12, 'fat' => 15]),
            'prepare_time' => 15,
            'total_time' => 30,
            'cooking_time' => 15,
            'servings' => 4,
            'steps' => json_encode(['Prepare fillings', 'Warm tortillas', 'Assemble tacos', 'Serve with toppings']),
            'cost' => 10.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Lasagna',
            'slug' => 'lasagna',
            'people_id' => 11,
            'rating' => 4.8,
            'category_id' => 12,
            'cuisine_id' => 11,
            'media_id' => 23,
            'description' => 'A layered pasta dish with meat, cheese, and tomato sauce.',
            'nutrition' => json_encode(['calories' => 600, 'protein' => 25, 'fat' => 30]),
            'prepare_time' => 30,
            'total_time' => 90,
            'cooking_time' => 60,
            'servings' => 6,
            'steps' => json_encode(['Prepare meat sauce', 'Layer ingredients', 'Bake lasagna', 'Serve hot']),
            'cost' => 25.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'title' => 'Apple Pie',
            'slug' => 'apple-pie',
            'people_id' => 12,
            'rating' => 4.6,
            'category_id' => 13,
            'cuisine_id' => 12,
            'media_id' => 25,
            'description' => 'A classic dessert with a flaky crust and sweet apple filling.',
            'nutrition' => json_encode(['calories' => 350, 'protein' => 4, 'fat' => 15]),
            'prepare_time' => 20,
            'total_time' => 60,
            'cooking_time' => 40,
            'servings' => 8,
            'steps' => json_encode(['Prepare crust', 'Make apple filling', 'Assemble pie', 'Bake and serve']),
            'cost' => 15.00,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
    }

}
